apiVersion: v1
kind: Service
metadata:
  name: backend-server-service
spec:
  type: NodePort
  selector:
    app: backend-server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http